// import { COUNTRY_CODES } from 'components/data/countryData';
// import { platformUrlGetter } from 'helpers/tradingPlatformHelper';

export const BROKER = {
  UMARKETS: 'umarkets',
  MAXIMARKETS: 'maximarkets',
  TRADEALLCRYPTO: 'tradeallcrypto',
  LIMEFX: 'limefx',
  MAXITRADE: 'maxitrade',
  DOWMARKETS: 'dowmarkets',
  LEXATRADE: 'lexatrade',
  GOLDFLAME: 'goldflame',
  IROTRADEX: 'irotradex',
  INVESTINGVIP: 'investingvip',
  POWERTREND: 'powertrend',
  // TRADIVA: 'tradiva',
  // '770CAPITAL': '770capital',
};

export const CALLERS = {
  'od-op': 'OpenDeal from Object Page',
  'od-pp': 'Open deal from post page',
  'od-pm': 'Open deal from post modal',
  'od-dp': 'OpenDeal from Discover Page',
  'od-pc': 'Open deal from post card',
  'cd-dp': 'Close deal from Deals Page',
};

export const BROKERS_LIST = Object.values(BROKER);

export const TVPlaylistId = 'PLvJR9G7c0HbYt1ulC9NVW9EiSk8N4sQjK';

export const BROKER_BY_LINK_ID = {
  'investarena-mm': BROKER.MAXIMARKETS,
  'media-fxpos-mailer-investarena-ru': BROKER.MAXIMARKETS,
  'promo-vip-group-jan-investarena-mm': BROKER.MAXIMARKETS,
  'investarena-um': BROKER.UMARKETS,
  'investarena-um-en': BROKER.UMARKETS,
  'promo-vip-group-jan-investarena-um': BROKER.UMARKETS,
  'investarena-lm': BROKER.LIMEFX,
  'promo-vip-group-jan-investarena-lm': BROKER.LIMEFX,
  'investarena-tac': BROKER.TRADEALLCRYPTO,
  'promo-vip-group-jan-investarena-tac': BROKER.TRADEALLCRYPTO,
  'investarena-gf-pl': BROKER.GOLDFLAME,
  'investarena-it-pl': BROKER.IROTRADEX,
  'investarena-mt-pl': BROKER.MAXITRADE,
  'investarena-dm-pl': BROKER.DOWMARKETS,
  'investarena-lt-pl': BROKER.LEXATRADE,
  'investarena-lt-en': BROKER.LEXATRADE,
  'investarena-iv-en': BROKER.INVESTINGVIP,
  'investarena-pt-ru': BROKER.POWERTREND,
};

export const PLATFORM_FACTOR = 1000000;

export const LIMIT_ORDER_TYPES = {
  LIMIT: 'LIMIT',
  STOP: 'STOP',
};

export const EDUCATION_LINKS = {
  [BROKER.UMARKETS]: {
    en: 'https://umarkets.info/learning/webinars/',
    es: 'https://umarkets.info/es/learning/webinars/',
    ru: 'https://umarkets.info/ru/learning/webinars/',
  },
  [BROKER.MAXIMARKETS]: {
    en: 'https://maximarkets.net/webinars/',
    ru: 'https://maximarkets.net/webinars/',
  },
  [BROKER.TRADEALLCRYPTO]: {
    en: 'https://tradeallcrypto.com/webinars/',
    ru: 'https://tradeallcrypto.org/webinars/',
  },
  [BROKER.LIMEFX]: {
    en: 'https://limefx.com/en/learning/videolessons/',
    ru: 'https://limefx.com/webinars/',
  },
  [BROKER.MAXITRADE]: {
    en: 'https://maxitrade.com/en/webinar/',
    ru: 'https://maxitrade.com/ru/webinar/',
    de: 'https://maxitrade.com/de/webinar/',
    pl: 'https://maxitrade.com/pl/webinar/',
  },
  [BROKER.DOWMARKETS]: {
    en: 'https://dowmarkets.com/pl/webinar/',
    pl: 'https://dowmarkets.com/pl/webinar/',
  },
  [BROKER.LEXATRADE]: {
    en: 'https://lexatrade.com/webinar/',
    es: 'https://lexatrade.com/es/education/',
    de: 'https://lexatrade.com/de/education/',
    pl: 'https://lexatrade.com/pl/webinar/',
  },
  [BROKER.GOLDFLAME]: {
    en: 'https://goldflame.io/webinars/',
    pl: 'https://goldflame.io/webinars/',
  },
  [BROKER.IROTRADEX]: {
    en: 'https://irotradex.com/webinar/',
    pl: 'https://irotradex.com/webinar/',
  },
  [BROKER.INVESTINGVIP]: {
    en: 'https://investingvip.com/en/',
    ru: 'https://investingvip.com/ru/',
  },
  [BROKER.POWERTREND]: {
    en: 'https://prtrend.org/vebinary/',
    ru: 'https://prtrend.org/vebinary/',
  },
};

// export const getEducationLink = platformUrlGetter(EDUCATION_LINKS);

// const {
//   AMERICAN_SAMOA,
//   BELARUS,
//   CANADA,
//   GUAM,
//   IRELAND,
//   ISRAEL,
//   KOSOVO,
//   LATVIA,
//   LITHUANIA,
//   NORTHERN_MARIANA_ISLANDS,
//   PUERTO_RICO,
//   ROMANIA,
//   RUSSIAN_FEDERATION,
//   SWITZERLAND,
//   UKRAINE,
//   UNITED_KINGDOM,
//   URUGUAY,
//   US_VIRGIN_ISLANDS,
//   USA,
// } = COUNTRY_CODES;
//
// export const PLATFORM_DEFAULT_COUNTRIES = {
//   [BROKER.MAXIMARKETS]: { DEFAULT: RUSSIAN_FEDERATION },
//   [BROKER.UMARKETS]: {
//     DEFAULT: SWITZERLAND,
//     ru: RUSSIAN_FEDERATION,
//   },
//   [BROKER.LIMEFX]: { DEFAULT: RUSSIAN_FEDERATION },
//   [BROKER.TRADEALLCRYPTO]: { DEFAULT: RUSSIAN_FEDERATION },
//   [BROKER.IROTRADEX]: { DEFAULT: UNITED_KINGDOM },
//   [BROKER.GOLDFLAME]: { DEFAULT: UNITED_KINGDOM },
//   [BROKER.MAXITRADE]: {
//     DEFAULT: UNITED_KINGDOM,
//     ru: RUSSIAN_FEDERATION,
//   },
//   [BROKER.DOWMARKETS]: {
//     DEFAULT: UNITED_KINGDOM,
//     ru: RUSSIAN_FEDERATION,
//   },
//   [BROKER.LEXATRADE]: { DEFAULT: UNITED_KINGDOM },
//   [BROKER.INVESTINGVIP]: { DEFAULT: UNITED_KINGDOM },
//   [BROKER.POWERTREND]: { DEFAULT: RUSSIAN_FEDERATION },
// };
//
// export const PLATFORM_PROHIBITED_COUNTRIES = {
//   [BROKER.MAXIMARKETS]: [
//     AMERICAN_SAMOA,
//     CANADA,
//     GUAM,
//     IRELAND,
//     ISRAEL,
//     NORTHERN_MARIANA_ISLANDS,
//     PUERTO_RICO,
//     UKRAINE,
//     US_VIRGIN_ISLANDS,
//     USA,
//   ],
//   [BROKER.UMARKETS]: [
//     AMERICAN_SAMOA,
//     CANADA,
//     GUAM,
//     IRELAND,
//     ISRAEL,
//     NORTHERN_MARIANA_ISLANDS,
//     PUERTO_RICO,
//     ROMANIA,
//     LATVIA,
//     LITHUANIA,
//     UKRAINE,
//     UNITED_KINGDOM,
//     URUGUAY,
//     US_VIRGIN_ISLANDS,
//     USA,
//   ],
//   [BROKER.LIMEFX]: [
//     AMERICAN_SAMOA,
//     BELARUS,
//     CANADA,
//     GUAM,
//     IRELAND,
//     ISRAEL,
//     NORTHERN_MARIANA_ISLANDS,
//     PUERTO_RICO,
//     US_VIRGIN_ISLANDS,
//     USA,
//   ],
//   [BROKER.TRADEALLCRYPTO]: [
//     AMERICAN_SAMOA,
//     CANADA,
//     GUAM,
//     IRELAND,
//     ISRAEL,
//     NORTHERN_MARIANA_ISLANDS,
//     PUERTO_RICO,
//     UKRAINE,
//     US_VIRGIN_ISLANDS,
//     USA,
//   ],
//   [BROKER.IROTRADEX]: [
//     AMERICAN_SAMOA,
//     CANADA,
//     GUAM,
//     IRELAND,
//     ISRAEL,
//     LATVIA,
//     LITHUANIA,
//     NORTHERN_MARIANA_ISLANDS,
//     PUERTO_RICO,
//     UKRAINE,
//     US_VIRGIN_ISLANDS,
//     USA,
//   ],
//   [BROKER.GOLDFLAME]: [
//     AMERICAN_SAMOA,
//     CANADA,
//     GUAM,
//     IRELAND,
//     ISRAEL,
//     LATVIA,
//     LITHUANIA,
//     NORTHERN_MARIANA_ISLANDS,
//     PUERTO_RICO,
//     UKRAINE,
//     US_VIRGIN_ISLANDS,
//     USA,
//   ],
//   [BROKER.MAXITRADE]: [
//     AMERICAN_SAMOA,
//     CANADA,
//     GUAM,
//     IRELAND,
//     ISRAEL,
//     LATVIA,
//     LITHUANIA,
//     NORTHERN_MARIANA_ISLANDS,
//     PUERTO_RICO,
//     UKRAINE,
//     US_VIRGIN_ISLANDS,
//     USA,
//   ],
//   [BROKER.DOWMARKETS]: [
//     AMERICAN_SAMOA,
//     CANADA,
//     GUAM,
//     IRELAND,
//     ISRAEL,
//     KOSOVO,
//     LATVIA,
//     LITHUANIA,
//     NORTHERN_MARIANA_ISLANDS,
//     PUERTO_RICO,
//     UKRAINE,
//     USA,
//     US_VIRGIN_ISLANDS,
//   ],
//   [BROKER.LEXATRADE]: [
//     AMERICAN_SAMOA,
//     CANADA,
//     GUAM,
//     IRELAND,
//     ISRAEL,
//     LATVIA,
//     LITHUANIA,
//     NORTHERN_MARIANA_ISLANDS,
//     PUERTO_RICO,
//     UKRAINE,
//     US_VIRGIN_ISLANDS,
//     USA,
//   ],
//   [BROKER.INVESTINGVIP]: [
//     AMERICAN_SAMOA,
//     CANADA,
//     GUAM,
//     IRELAND,
//     ISRAEL,
//     NORTHERN_MARIANA_ISLANDS,
//     PUERTO_RICO,
//     ROMANIA,
//     LATVIA,
//     LITHUANIA,
//     US_VIRGIN_ISLANDS,
//     USA,
//   ],
//   [BROKER.POWERTREND]: [
//     AMERICAN_SAMOA,
//     CANADA,
//     GUAM,
//     IRELAND,
//     ISRAEL,
//     LATVIA,
//     LITHUANIA,
//     NORTHERN_MARIANA_ISLANDS,
//     PUERTO_RICO,
//     UKRAINE,
//     US_VIRGIN_ISLANDS,
//     USA,
//   ],
// };
//
// export const PLATFORM_LANGUAGES = {
//   [BROKER.MAXIMARKETS]: ['RU'],
//   [BROKER.UMARKETS]: ['RU', 'EN', 'ES', 'DE', 'PT'],
//   [BROKER.LIMEFX]: ['RU'],
//   [BROKER.TRADEALLCRYPTO]: ['RU'],
//   [BROKER.IROTRADEX]: ['PL'],
//   [BROKER.GOLDFLAME]: ['PL'],
//   [BROKER.MAXITRADE]: ['RU', 'EN', 'ES', 'DE', 'PL'],
//   [BROKER.DOWMARKETS]: ['RU', 'EN', 'DE', 'PL'],
//   [BROKER.LEXATRADE]: ['EN', 'ES', 'DE', 'PL'],
//   [BROKER.INVESTINGVIP]: ['EN', 'RU'],
//   [BROKER.INVESTINGVIP]: ['RU'],
// };
